model:
  in_channels: 19
  patch_size: 4
  embed_dim: 1152
  num_heads: 8
  num_layers: 12
  num_classes1: 3
  num_classes2: 1858

training:
  batch_size: 4
  num_epochs: 3
  learning_rate: 0.001
  weight_decay: 0.01

data:
  num_samples: 1000
  input_size: 8